console.log('Olá, esse programa remove espaçamentos')
console.log('Além disso, deixa toda palavra maiúscula!')
console.log('Vamos testar?')
frase = prompt('Digite uma frase de sua preferência: ')
console.log(frase.toUpperCase().trim())